### ISSUE TITLE
Fix pull label action

### ISSUE THREAD

**Issue by eduardojdiniz** [gpnlab/ml_template#3]
@nxdens I tried opening a pull request to test the labeling action, and it's failing. I did some digging, but I am not well-versed on pre-commit and git hooks. Could you Assist? :sweat_smile: 

Here is what I found:
```
// Ensure you have both these files
.github/workflows/labeler.yml   // with the action
.github/labeler.yml        //with your labels
```
I am not sure how the label action is configured in the pre-commit workflow, so may not be relevant.

**Comment by nxdens** [comment]
I'm not entirely sure either but I will play around with it

**Comment by nxdens** [comment]
The issue is that we did not create any labels so the labeler couldn't assign a label to anything 😅 I will merge i fix from my fork

**Comment by eduardojdiniz** [comment]
Reopening to link it to the pull request. It will automatically close once I merge :smiley: 
So, for future reference, it was just a matter of adding the `.github/labeler.yml` file, right?
